@url = "http://39.106.169.248:8080"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTU5MDA0NjksImlkIjoxLCJuYmYiOjE1OTU5MDA0NjksInVzZXJuYW1lIjoieHl4MTA3In0.P6u0Ey9NGt3QEmhhGiwW9XiREy4S_skhEHJTvtiFKZ4
Authorization: yxy {{token}}
Content-Type: application/json

{
    "title": "如何吃饭",
    "content": "如何吃饭的发生，到底需要如何做到，不如何吃饭的发生，又会如何产生。 要想清楚，如何吃饭，到底是一种怎么样的存在。 而这些并不是完全重要，不得不考虑它出现了的事实。 生活中，若如何吃饭出现了，我们就不得不考虑它出现了的事实。 那么， 叔本华曾经提到过，意志是一个强壮的盲人，倚靠在明眼的跛子肩上。这不禁令我深思。",
    "tag": "安装"
}
###
GET http://127.0.0.1:3000/users

###
POST http://127.0.0.1:8080/register
Content-Type: application/json

{
    "username": "archerx",
    "email": "985830672@qq.com",
    "password": "archerx",
    "code": '693430'
},

###
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
    "username": "archerx",
    "password": "archerx",
},

###
POST http://127.0.0.1:8080/code
Content-Type: application/json

{
    "email": "985830672@qq.com"
}

###
POST http://127.0.0.1:8080/admin
Content-Type: application/json
Authorization: yxy {{token}}

###
POST   http://127.0.0.1:8080/comment
Content-Type: application/json
Authorization: yxy {{token}}

{
  "articleId": 1,
  "content": "string",
  "parentId": 0
}

###
put http://127.0.0.1:8080/article/1
Content-Type: application/json
Authorization: yxy {{token}}

{
    "title": "如何吃饭2",
    "content": "<h2>首先</h2><h4>如何吃饭的发生，到底需要如何做到，不如何吃饭的发生，又会如何产生。 要想清楚，如何吃饭，到底是一种怎么样的存在。 而这些并不是完全重要，不得不考虑它出现了的事实。 生活中，若如何吃饭出现了，我们就不得不考虑它出现了的事实。 那么， 叔本华曾经提到过，意志是一个强壮的盲人，倚靠在明眼的跛子肩上。这不禁令我深思。</h4>"
}

###
POST http://139.129.97.214:8080/article
Content-Type: application/json
Authorization: yxy {{token}}

{
    "title": "1",
    "content": "1",
    "tag": "1"
}

###
GET  http://127.0.0.1:8080/article/
Content-Type: application/json
Authorization: yxy {{token}}
