@url = "http://127.0.0.1:8085"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDIzNzkxMzYsImlkIjoyLCJuYmYiOjE2MDIzNzkxMzYsInVzZXJuYW1lIjoieHl4MTA3In0.geqBrVBG_QAxhAifhMjzz8yMv_DNm-F2j4oCQiDGu9Q
Authorization: yxy {{token}}
Content-Type: application/json

{
    "title": "如何吃饭",
    "content": "如何吃饭的发生，到底需要如何做到，不如何吃饭的发生，又会如何产生。 要想清楚，如何吃饭，到底是一种怎么样的存在。 而这些并不是完全重要，不得不考虑它出现了的事实。 生活中，若如何吃饭出现了，我们就不得不考虑它出现了的事实。 那么， 叔本华曾经提到过，意志是一个强壮的盲人，倚靠在明眼的跛子肩上。这不禁令我深思。",
    "tag": "安装"
}
###
GET http://127.0.0.1:8085/users

###
POST http://127.0.0.1:8085/register
Content-Type: application/json

{
    "username": "archerx",
    "email": "1297184665@qq.com",
    "password": "archerx",
    "code": "251708"
},

###
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "xingyu",
    "password": "123456",
},

###
POST http://127.0.0.1:8085/code
Content-Type: application/json

{
    "email": "985830672@qq.com"
}

###
POST http://127.0.0.1:8085/admin
Content-Type: application/json
Authorization: yxy {{token}}

###
POST   http://127.0.0.1:8085/comment
Content-Type: application/json
Authorization: yxy {{token}}

{
  "articleId": 1,
  "content": "string",
  "parentId": 0
}

###
put http://127.0.0.1:8085/article/1
Content-Type: application/json
Authorization: yxy {{token}}

{
    "title": "如何吃饭2",
    "content": "<h2>首先</h2><h4>如何吃饭的发生，到底需要如何做到，不如何吃饭的发生，又会如何产生。 要想清楚，如何吃饭，到底是一种怎么样的存在。 而这些并不是完全重要，不得不考虑它出现了的事实。 生活中，若如何吃饭出现了，我们就不得不考虑它出现了的事实。 那么， 叔本华曾经提到过，意志是一个强壮的盲人，倚靠在明眼的跛子肩上。这不禁令我深思。</h4>"
}

###
POST http://127.0.0.1:8085/article
Content-Type: application/json
Authorization: yxy {{token}}

{
    "title": "1",
    "content": "1",
    "tag": "1"
}

###
POST  http://127.0.0.1:8085/article/page
Content-Type: application/json
Authorization: yxy {{token}}

{
    "page": "1"
}

###
POST  http://127.0.0.1:3000/getCode
Content-Type: application/json
# Authorization: yxy {{token}}

{
    "email": "985830672@qq.com"
}

###
GET  http://127.0.0.1:3000/users
Content-Type: application/json
# Authorization: yxy {{token}}
