@url = "http://39.106.169.248:8080"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODMwMzIxNjQsImlkIjo0LCJuYmYiOjE1ODMwMzIxNjQsInVzZXJuYW1lIjoiYWFhYWEifQ.q4Q_oNoVZk7C6GZdpS5ZeycxNZOvanoiC4GEkWr-lpA
POST  {{url}}/article
Authorization: yxy {{token}}
Content-Type: application/json

{
    "title": "如何吃饭",
    "content": "如何吃饭的发生，到底需要如何做到，不如何吃饭的发生，又会如何产生。 要想清楚，如何吃饭，到底是一种怎么样的存在。 而这些并不是完全重要，不得不考虑它出现了的事实。 生活中，若如何吃饭出现了，我们就不得不考虑它出现了的事实。 那么， 叔本华曾经提到过，意志是一个强壮的盲人，倚靠在明眼的跛子肩上。这不禁令我深思。",
    "tag": "安装"
}
###
GET http://127.0.0.1:3000/users
